### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by BlackYuzia** [kamikazekuh/WCS_GO#4]
@kamikazekuh 
![image](https://user-images.githubusercontent.com/25010528/42336193-9ddb942e-808b-11e8-8eb7-b6a7d96598c6.png)
Hi,
I get some errors. I did somethink wrong?

**Comment by kamikazekuh** [comment]
Thank you for reporting, should be fixed in the latest version

**Comment by BlackYuzia** [comment]
@kamikazekuh 
![image](https://user-images.githubusercontent.com/25010528/42340294-53a14ec8-8098-11e8-9511-99039e3f52b6.png)
after start map, another error.

**Comment by kamikazekuh** [comment]
I do not get this error when testing levelbank, but I added a check to see if the player is loaded yet, so this should not happen again
